language: ruby
rvm:
  - "1.9.3"
before_script:
  - psql -c 'create role todayiate login;' -U postgres
  - psql -c 'create database todayiate_test;' -U postgres
  - bundle exec rake db:migrate db:test:prepare
